spring.application.name=Online_Learning_Portal
# JPA properties
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost/olp_db

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.username=root

spring.datasource.password=Patil@123
spring.jpa.hibernate.ddl-auto=update
# Dialect is used to convert all datatype of java into datatypes of SQL . Here,mySQl 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Folder location for storing uploaded files
file.upload-dir=uploads
# Razorpay Configuration
razorpay.key_id=YOUR_KEY_ID
razorpay.key_secret=YOUR_KEY_SECRET
